language: go

go:
  - 1.6

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go build  github.com/BPing/aliyun-live-go-sdk/client
  - go build  github.com/BPing/aliyun-live-go-sdk/device
  - go build  github.com/BPing/aliyun-live-go-sdk/device/cdn
  - go build  github.com/BPing/aliyun-live-go-sdk/device/live
  - go build  github.com/BPing/aliyun-live-go-sdk/util
  - go test -v github.com/BPing/aliyun-live-go-sdk/device
  - go test -v github.com/BPing/aliyun-live-go-sdk/client -covermode=count -coverprofile=clientcoverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=clientcoverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -v github.com/BPing/aliyun-live-go-sdk/util -covermode=count -coverprofile=utilcoverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=utilcoverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

